import itertools
import re
from unidecode import unidecode

def english_conversion(text):
    ROUND_S_BEFORE_BK = False # True in 17th and early 18th century
    
    if ROUND_S_BEFORE_BK:
        # selects every S that has a letter after it,
        # so long as that letter is not B nor K.
        pattern = r"s(?=[a-ac-jm-zA-AC-JM-Z])"
    else:
        # selects every S that has any letter after it.
        pattern = r"s(?=[a-zA-Z])"
    indices = [m.start() for m in re.finditer(pattern, text)]

    # excludes any S that comes before or after the letter F.
    pattern = r"s(?=f|F)|(?<=f|F)s"
    excluded_indices = [m.start() for m in re.finditer(pattern, text)]
    indices = [i for i in indices if i not in excluded_indices]
    for i in indices:
        text = text[:i] + "ſ" + text[i + 1: ]

    # replaces any occurrence of "ſſſ" with "ſsſ".
    pattern = r"ſſſ"
    indices = [m.start() for m in re.finditer(pattern, text)]
    for i in indices:
        text = text[:i] + "ſsſ" + text[i + 3: ]

    return text

_REPLACEMENTS = {
    "bonapartismus": "bonapartismus",
    "chartismus": "chartismus",
    "tripartismus": "tripartismus",
    "herbergssuche": "herbergsſuche",
    "tausalz": "tauſalz",
    "trausaal": "trauſaal",
    "bernsdorf": "bernsdorf",
    "bertoldsbrunnen": "bertoldsbrunnen",
    "kentumsprache": "kentumſprache",
    "thalassämie": "thalaſſämie",
    "thalassämien": "thalaſſämien",
    "essäpfel": "eſsäpfel",
    "dreiflüssestadt": "dreiflüſseſtadt",
    "dreiflüssestädte": "dreiflüſseſtädte",
    "odessa": "odeſſa",
    "vanessa": "vaneſſa",
    "alessandro": "aleſſandro",
    "intrauterinpessar": "intrauterinpeſſar",
    "vasall": "vaſall",
    "basal": "baſal",
    "lassalle": "laſſalle",
    "nasal": "naſal",
    "knosso": "knoſſo",
    "kassapreise": "kaſſapreise",
    "hausterrasse": "hausterraſſe",
    "austral": "auſtral",
    "inkasso": "inkaſſo",
    "isobut": "iſobut",
    "isoba": "iſoba",
    "lassob": "laſſob",
    "espresso": "espreſſo",
    "lebensodem": "lebensodem",
    "arbeitsoverall": "arbeitsoverall",
    "crossover": "croſsover",
    "passow": "paſſow",
    "lomonossow": "lomonoſſow",
    "dissert": "diſſert",
    "baſſetrüden": "baſſetrüden",
    "setymologie": "setymologie",
    "eschatologie": "eschatologie",
    "sadressat": "sadreſſat",
    "adressat": "adreſſat",
    "auster": "auſter",
    "baseballs": "baſeballſ", # UNCERTAIN
    "baseball": "baſeball", # UNCERTAIN
    "gottessöhne": "gottesſöhne",
    "renaissance": "renaiſſance",
    "bessarab": "beſsarab",
    "essay": "eſſay",
    "somelett": "somelett",
    "ssattel": "sſattel",
    "sattel": "ſattel",
    "ssattler": "sſattler",
    "sattler": "ſattler",
    "ssediment": "sſediment",
    "sediment": "ſediment",
    "sethik": "sethik",
    "sethisch": "sethiſch",
    "sessig": "seſſig",
    "syoga": "syoga",
    "lissabon": "liſſabon",
    "melissa": "meliſſa",
    "nissan": "niſſan",
    "orissa": "oriſſa",
    "clarissa": "clariſſa",
    "chamisso": "chamiſſo",
    "pissoir": "piſſoir",
    "glossar": "gloſſar",
    "ossarium": "oſſarium",
    "passat": "paſſat",
    "briefaustausch": "briefaustauſch",
    "nikolaustag": "nikolaustag",
    "schauspiel": "ſchauſpiel",
    "grausam": "grauſam",
    "klausu": "klauſu",
    "hausung": "hauſung",
    "kolossal": "koloſſal",
    "plateaus": "plateauſ",
    "mausole": "mauſole",
    "bussard": "buſſard",
    "russisch": "ruſſiſch",
    "mussolini": "muſſolini",
    "perkussorisch": "perkuſſoriſch",
    "schance": "schance",
    "townsend": "townsend",
    "abschor": "abſchor",
    "bisschen": "biſschen",
    "genauso": "genauſo",
    "derselb": "derſelb",
    "dieselb": "dieſelb",
    "dasselb": "dasſelb",
    "denselb": "denſelb",
    "demselb": "demſelb",

    "sideal": "sideal",
    "sidee": "sidee",
    "sadress": "sadreſſ",
    "adressi": "adreſſi",
    "adress": "adreſs",
    "beeinflusser": "beeinfluſſer",
    "flussen": "fluſſen",
    "fluss": "fluſs",
    "interessant": "intereſſant",
    "sinteresse": "sintereſſe",
    "interesse": "intereſſe",
    "jahressi": "jahresſi",
    "kommissar": "kommiſſar",
    "kommissär": "kommiſſär",
    "skongresses": "skongreſses",
    "kongresses": "kongreſses",
    "skongresse": "skongreſſe",
    "kongresse": "kongreſſe",
    "skongress": "skongreſs",
    "kongress": "kongreſs",
    "messes": "meſſeſ",
    "messen": "meſſen",
    "messa": "meſsa",
    "ssystems": "sſyſtemſ",
    "ssystem": "sſyſtem",
    "system": "ſyſtem",
    #"messer": "meſſer",
    "messu": "meſsu",
    "messins": "meſsinſ",
    "missach": "miſsach",
    "prozesses": "prozeſses",
    "prozesse": "prozeſſe",
    "prozess": "prozeſs",
    "sache": "ſache",
    "ssöl": "ſsöl",

    "sschossest": "sſchoſſeſt",
    "sschosses": "sſchoſses",
    "sschossen": "sſchoſſen",
    "sschlossest": "sſchloſſeſt",
    "sschlosses": "sſchloſses",
    "sschlossen": "sſchloſſen",
    "sschlosser": "sſchloſſer",
    "sschloss": "sſchloſs",
    "sschlusses": "sſchluſses",
    "sschluss": "sſchluſs",
    "sstoff": "sſtoff",

    "schossest": "ſchoſſeſt",
    "schosses": "ſchoſses",
    "schossen": "ſchoſſen",
    "schlossest": "ſchloſſeſt",
    "schlosses": "ſchloſses",
    "schlossen": "ſchloſſen",
    "schlosser": "ſchloſſer",
    "schloss": "ſchloſs",
    "schlusses": "ſchluſses",
    "schluss": "ſchluſs",
    "stoff": "ſtoff",

    "sselbs": "sſelbſ",
    "selbs": "ſelbſ",

    # aus
    "sausarbeit": "sausarbeit",
    "ausarbeit": "ausarbeit",
    "bausa": "bauſa",
    "kausa": "kauſa",
    "schausa": "ſchauſa",
    "ausa": "ausa",

    "hausä": "hausä",
    "ausä": "auſä",

    "sausen": "ſauſen",
    "ausen": "auſen",
    "sauses": "ſauſeſ",
    "auses": "auseſ",

    "ausib": "auſib",
    "ausic": "auſic",
    "ausid": "ausid",
    "hausim": "hausim",
    "ausim": "auſim",
    "hausin": "hausin",
    "ausin": "auſin",
    "ausip": "auſip",
    "ausisch": "auſiſch",
    "ausit": "auſit",

    "bauso": "bauſo",
    "auso": "auso",

    "ausu": "ausu",

    "ausüb": "ausüb",
    "ausü": "auſü",

    "auss": "ausſ",
    "bausp": "bauſp",
    "sausp": "sausp",
    "ausp": "ausp",

    "saustrag": "saustrag",
    "austrag": "austrag",
    "saustrieb": "saustrieb",
    "austrieb": "austrieb",
    "saustritt": "saustritt",
    "austritt": "austritt",
    "saustausch": "saustauſch",
    "austausch": "austauſch",
    "saustreibung": "saustreibung",
    "austreibung": "austreibung",
    "baust": "bauſt",
    "caust": "cauſt",
    "daust": "daust",
    "ffaust": "ffaust",
    "faust": "fauſt",
    "gaust": "gaust",
    "laust": "lauſt",
    "naust": "naust",
    "pfaust": "pfaust",
    "paust": "pauſt",
    "raust": "rauſt",
    "saust": "ſauſt",
    "taust": "tauſt",
    "zaust": "zauſt",
    "volkss": "volksſ",
    "volks": "volks",
    "fensters": "fenſterſ",
    "fenster": "fenſter",

    # sch- combos
    "sscha": "sſcha",
    "sschä": "sſchä",
    "sschi": "sſchi",
    "sscho": "sſcho",
    "sschö": "sſchö",
    "sschu": "sſchu",
    "sschü": "sſchü",

    #"sscha": "sſcha",
    "schä": "ſchä",
    "schi": "ſchi",
    "scho": "ſcho",
    "schö": "ſchö",
    "schu": "ſchu",
    "schü": "ſchü",
    "schy": "ſchy",

    "schb": "ſchb",
    "schc": "ſchc",
    "schd": "ſchd",
    "schf": "ſchf",
    "schg": "ſchg",
    "schh": "ſchh",
    "schj": "ſchj",
    "schk": "ſchk",
    "schl": "ſchl",
    "schm": "ſchm",
    "schn": "ſchn",
    "schp": "ſchp",
    "schq": "ſchq",
    "schs": "ſchſ",
    "scht": "ſcht",
    "schv": "ſchv",
    "schw": "ſchw",
    "schy": "ſchy",
    "schz": "ſchz",
    "ssch": "sſch",

    "ückss": "ücksſ",
    "ücks": "ücks",

    # s proceeded by consonants.
    "bss": "bsſ",
    "css": "cſſ",
    "dss": "dsſ",
    "fss": "fsſ",
    "gss": "gsſ",
    "hss": "hsſ",
    "jss": "jſſ",
    "kss": "ksſ",
    "lss": "lsſ",
    "mss": "msſ",
    "nss": "nsſ",
    "pss": "psſ",
    "rss": "rsſ",
    "sss": "ſsſ",
    "tss": "tsſ",
    "wss": "wsſ",

    "cs": "cſ",
    "ks": "kſ",
    "ßs": "ßſ",
    "xs": "xſ",
    "zs": "zſ",

    # occurrences, mostly with double letters of some kind.
    "ssassi": "ſsaſſi",
    "ssabot": "sſabot",
    "ssall": "ſsall",
    "ssamm": "sſamm",
    "ssapp": "ſsapp",
    "ssatt": "ſsatt",
    "ssab": "ſsab",
    "ssac": "sſac",
    "ssap": "ſsap",
    "ssar": "ſſar",
    "ssay": "ſſay",
    "sadd": "ſadd",
    "saff": "ſaff",
    "sagg": "sagg",
    "sakk": "sakk",
    "sall": "sall",
    "samm": "ſamm",
    "sannahm": "sannahm",
    "sannä": "sannä",
    "sapp": "sapp",
    "sarr": "sarr",
    "sassi": "saſſi",
    "satt": "satt",
    "sabot": "ſabot",
    "sab": "sab",
    "saj": "ſaj",
    "saq": "saq",   
    "saw": "ſaw",

    "ssäb": "sſäb",
    "ssäc": "sſäc",
    "ssäf": "sſäf",
    "ssäg": "sſäg",
    "ssäl": "sſäl",
    "ssät": "sſät",
    "sänn": "ſänn",
    "säss": "ſäſſ",
    "sätt": "ſätt",
    "ssä": "sſä",

    "ssesch": "ſſeſch",
    "sseff": "ſseff",
    "ssell": "ſſell",
    "sserr": "ſſerr",
    "ssett": "ſſett",
    "sseb": "ſſeb",
    "ssed": "ſſed",
    "ssenn": "ſſenn",
    "ssef": "ſſef",
    "ssels": "ſſelſ",
    "ssens": "ſſenſ",
    "ssev": "ſſev",
    "sesch": "ſeſch",
    "seff": "seff",
    "sell": "ſell",
    "sels": "ſelſ",
    "semm": "ſemm",
    "senn": "ſenn",
    "serr": "ſerr",
    "sess": "ſeſſ",
    "sett": "ſett",
    "sef": "ſef",
    "sev": "ſev",

    "ssionss": "ſſionsſ",
    "ssions": "ſſionsſ",
    "ssisch": "ſſiſch",
    "ssipp": "sſipp",
    "ssitt": "sſitt",
    "ssib": "ſſib",
    "ssic": "sſic",
    "ssid": "sſid",
    "ssif": "ſſif",
    "ssik": "ſſik",
    "ssio": "ſſio",
    "ssir": "sſir",
    "ssit": "sſit",
    "ssiz": "ſſiz",
    "siff": "ſiff",
    "sirr": "sirr",
    "sitt": "ſitt",
    "sivv": "ſſiv",
    "sisch": "ſiſch",
    "sib": "ſib",
    "sic": "ſic",
    "sid": "ſid",
    "sie": "ſie",
    "sif": "ſif",
    "sik": "ſik",
    "siv": "ſiv",
    "siw": "ſiw",

    "ssonn": "sſonn",
    "ssorr": "ſſorr",
    "ssob": "ſsob",
    "ssoc": "sſoc",
    "ssog": "sſog",
    "ssoh": "sſoh",
    "ssok": "ſsok",
    "ssol": "sſol",
    "ssom": "sſom",
    "sson": "sſon",
    "ssop": "ſsop",
    "ssow": "sſow",
    "ssoz": "sſoz",
    "sonn": "ſonn",
    "sope": "sope",
    "sopp": "ſopp",
    "sorr": "ſorr",
    "sob": "sob",
    "soc": "ſoc",
    "sod": "ſod",
    "soj": "ſoj",
    "sol": "ſol",
    "som": "ſom",
    "son": "ſon",
    "sov": "ſov",
    "sow": "ſow",
    "soz": "ſoz",

    "ssöh": "sſöh",
    "ssök": "ſsök",
    "ssöl": "ſsöl",
    "ssöm": "sſöm",
    "ssön": "sſön",
    "söc": "ſöc",
    "söd": "söd",
    "söf": "söf",
    "sög": "ſög",
    "söh": "ſöh",
    "sök": "sök",
    "söm": "ſöm",
    "sön": "ſön",
    "sör": "ſör",
    "sös": "söſ",

    "ssungen": "ſſungen",
    "ssungss": "ſſungsſ",
    "ssungs": "ſſungs",
    "ssuff": "sſuff",
    "ssumm": "sſumm",
    "ssung": "ſſung",
    "ssub": "sſub",
    "ssuc": "sſuc",
    "ssuh": "ſsuh",
    "ssul": "sſul",
    "ssup": "sſup",

    "sungen": "ſungen",
    "sungss": "ſungsſ",
    "sungs": "ſungs",
    # "sungss": 
    "suff": "ſuff",
    "sugg": "ſugg",
    "sukk": "ſukk",
    "summ": "ſumm",
    "sung": "ſung",
    "sunn": "ſunn",
    "sub": "ſub",
    "suc": "ſuc",
    "sud": "ſud",
    "suh": "suh",
    "sul": "ſul",
    "sup": "ſup",
    "sut": "sut",

    #"ssüb": "ſsüb",
    #"ssüc": "sſüc",
    #"ssüd": "sſüd",
    #"ssül": "sſül",
    #"ssün": "sſün",
    #"ssüp": "sſüp",
    "ssü": "sſü",
    "süb": "süb",
    "süc": "ſüc",
    "süd": "ſüd",
    "süf": "ſüf",
    "süh": "ſüh",
    "sül": "ſül",
    "süm": "ſüm",
    "sün": "ſün",
    "süp": "ſüp",

    "ssy": "sſy",
    "sy": "ſy",

    # terms starting with s and ending with t + consonant.
    "ssatg": "ſſatg",
    "ssatk": "ſſatk",
    "ssatm": "ſsatm",
    "ssatr": "ſsatr",
    "ssatz": "sſatz",
    "satg": "ſatg",
    "sath": "sath",
    "satk": "ſatk",
    "satl": "satl",
    "satm": "satm",
    "satr": "satr",
    "satz": "ſatz",
    
    "ssätz": "sſätz",
    "sätz": "ſätz",
    
    "sseth": "ſſeth",
    "ssetr": "ſſetr",
    "ssety": "ſſety",
    "ssetz": "sſetz",
    "setb": "ſetb",
    "setd": "ſetd",
    "setf": "ſetf",
    "setg": "ſetg",
    "seth": "ſeth",
    "setk": "ſetk",
    "setl": "ſetl",
    "setm": "ſetm",
    "setp": "ſetp",
    "setr": "ſetr",
    "sets": "ſetſ",
    "setw": "ſetw",
    "sety": "ſety",
    "setz": "ſetz",
    
    "ssitz": "sſitz",
    "sition": "ſition",
    "sitb": "ſitb",
    "sitc": "ſitc",
    "sitd": "ſitd",
    "sitf": "ſitf",
    "sitg": "ſitg",
    "sith": "ſith",
    "sitk": "ſitk",
    "sitl": "ſitl",
    "sitm": "ſitm",
    "sitn": "ſitn",
    "sitp": "ſitp",
    "sitr": "ſitr",
    "sits": "ſitſ",
    "sitv": "ſitv",
    "sitw": "ſitw",
    "sity": "ſity",
    "sitz": "ſitz",

    "soth": "ſoth",
    "sotr": "ſotr",

    # s with eszett
    "saß": "ſaß",
    "soß": "ſoß",
    "söß": "ſöß",
    "süß": "ſüß",

    # double s with vowels
    "sassoz": "saſſoz",
    "assa": "aſſa",
    "assä": "asſä",
    "assest": "aſſeſt",
    "asses": "aſseſ",
    "asse": "aſſe",
    "assi": "aſſi",
    "assoz": "aſſoz",
    "assö": "aſsö",
    "assu": "aſſu",
    "assü": "aſsü",
    "assyr": "aſſyr",
    "assy": "asſy",
    "assas": "aſſaſ",

    "ässer": "äſſer",
    "ässes": "äſſeſ",
    "ässe": "äſſe",
    "ässi": "äſſi",
    "ässu": "äſſu",

    "essatt": "eſsatt",
    "essas": "eſsaſ",
    "essan": "eſsan",
    "essar": "eſsar",
    "essä": "esſä",
    "essest": "eſſeſt",
    "esses": "eſseſ",
    "esse": "eſſe",
    "essi": "eſſi",
    "esso": "eſſo",
    "essö": "esſö",
    "essy": "esſy",

    "rissa": "riſsa",
    "issa": "isſa",
    "issä": "isſä",
    "issest": "iſſeſt",
    "isses": "iſseſ",
    "isse": "iſſe",
    "issi": "iſſi",
    "isso": "isſo",
    "issö": "iſsö",

    "ossac": "oſsac",
    "ossam": "oſſam",
    "ossar": "oſsar",
    "ossest": "oſſeſ",
    "osses": "oſseſ",
    "osse": "oſſe",
    "ossi": "oſſi",
    "ossoc": "osſoc",
    "osso": "osſo",
    "ossö": "oſsö",
    "ossu": "oſſu",
    "ossü": "osſü",

    "össe": "öſſe",
    "össi": "öſſi",

    "aussa": "ausſa",
    "ussa": "uſsa",
    "ussest": "uſſeſt",
    "usses": "uſseſ",
    "usse": "usſe",
    #"ussi": "uſsi", # UNCERTAIN
    "gusso": "guſso",
    "usso": "usſo",
    "ussö": "usſö",
    "ussung": "uſſung",
    "ussu": "usſu",

    "üsse": "üſſe",
    "üssi": "üſſi",

    "ysse": "yſſe",

    # suffixes.
    "bars": "barſ",
    "becks": "beckſ",
    "bergs": "bergſ",
    "bührens": "bührenſ",
    "chors": "chorſ",
    "fachs": "fachſ",
    "fähigs": "fähigſ",
    "einfalts": "einfalts",
    "sorgfältig": "ſorgfältig",
    "sorgfalts": "ſorgfalts",
    "sorgfalt": "ſorgfalt",
    "falts": "faltſ",
    "farbens": "farbenſ",
    "fertigs": "fertigſ",
    "förmigs": "förmigſ",
    "freis": "freiſ",
    "gens": "genſ",
    "gleichs": "gleichs",
    "grafs": "grafſ",
    "graphies": "graphieſ",
    "schaft": "ſchaft",
    "schafts": "ſchafts",
    "hafts": "hafts",
    "halbers": "halberſ",
    "hausens": "hauſens",
    "heims": "heimſ",
    "heits": "heits",
    "igste": "igſte",
    "keits": "keitſ",
    "kens": "kenſ",
    "kraties": "kratieſ",
    "kundes": "kundeſ",
    "leis": "leiſ",
    "leins": "leinſ",
    "lekts": "lektſ",
    "lers": "lerſ",
    "lichs": "lichſ",
    "lings": "lings",
    "loges": "logeſ",
    "logies": "logieſ",
    "lyses": "lyſeſ",
    "mals": "malſ",
    "metries": "metrieſ",
    "nisse": "niſſe",
    "pathies": "pathieſ",
    "reichst": "reichſt",
    "reichs": "reichs",
    "richs": "richſ",
    "sals": "ſalſ",
    "sams": "ſamſ",
    "sans": "sanſ",
    "sches": "ſcheſ",
    "seits": "ſeits",
    "sels": "ſelſ",
    "sens": "ſenſ",
    # "skopies": "skopieſ", # UNCERTAIN: endos(ſ)kopie?
    "stes": "ſteſ",
    "steins": "ſteinſ",
    "tions": "tions",
    "trops": "tropſ",
    "tums": "tums",
    "volls": "vollſ",
    "wärts": "wärts",
    "weise": "weiſe",
    "werks": "werkſ",
    "werts": "wertſ",
    "wesen": "weſen",
    "witzs": "witzſ",
    "syls": "ſylſ",
    "syl": "ſyl",
    "yls": "ylſ",
}

_START_REPLACEMENTS = {
    "aus": "aus",
    "heraus": "heraus",
    "hinaus": "hinaus",
    "voraus": "voraus",
    "raus": "raus",
    "schwangers": "schwangerſ",
    "aufnahmes": "aufnahmeſ",
    "begräbnis": "begräbnis",
    "gefängnis": "gefängnis",
    "herkunfts": "herkunfts",
    "ankunfts": "ankunfts",
    "aufwärts": "aufwärts",
    "business": "buſineſs",
    "wellness": "wellneſs",
    "zahlungs": "zahlungs",
    "zukunfts": "zukunfts",
    "abgangs": "abgangs",
    "abwärts": "abwärts",
    "alltags": "alltags",
    "anfangs": "anfangs",
    "bistums": "bistums",
    "diagnos": "diagnoſ",
    "eiskunst": "eiskunſt",
    "entwäss": "entwäſſ",
    "erpress": "erpreſſ",
    "fitness": "fitneſs",
    "fäulnis": "fäulnis",
    "geburts": "geburts",
    "handels": "handels",
    "kondens": "kondens",
    "omnibus": "omnibus",
    "schaums": "ſchaums",
    "schloss": "ſchloſs",
    "schluss": "ſchluſs",
    "schlüssel": "ſchlüſſel",
    "seewasser": "seewaſſer",
    "standes": "ſtandes",
    "univers": "univerſ",
    "vertaus": "vertauſ",
    "zeugnis": "zeugnis",
    "zufalls": "zufalls",
    "ablass": "ablaſs",
    "abriss": "abriſs",
    "abwassers": "abwaſſerſ",
    "abwasser": "abwaſſer",
    "ananas": "ananas",
    "anpass": "anpaſs",
    "anweis": "anweis",
    "auslös": "auslöſ",
    "ausrüs": "ausrüſ",
    "begeis": "begeiſ",
    "bemess": "bemeſs",
    "bewuss": "bewuſſ",
    "bewässer": "bewäſſer",
    "bundes": "bundes",
    "dazwischen": "dazwiſchen",
    "diözes": "diözes",
    "empors": "emporſ",
    "englisch": "engliſch",
    "erfass": "erfaſs",
    "ermessens": "ermeſſens",
    "gebiss": "gebiſs",
    "genuss": "genuſs",
    "geräusch": "geräuſch",
    "gewässer": "gewäſſer",
    "gottes": "gottes",
    "gymnas": "gymnaſ",
    "hufeisen": "hufeiſen",
    "imbiss": "imbiſs",
    "impuls": "impuls",
    "jahres": "jahres",
    "kampfs": "kampfſ",
    "kaukas": "kaukas",
    "nordost": "nordoſt",
    "orchest": "orcheſt",
    "pfingst": "pfingſt",
    "relais": "relais",
    "repräs": "repräſ",
    "stroms": "ſtromſ",
    "tennis": "tennis",
    "unwissens": "unwiſſens",
    "unwissen": "unwiſſen",
    "zyklus": "zyklus",
    "abgas": "abgas",
    "abges": "abgeſ",
    "ablös": "ablöſ",
    "abrüs": "abrüſ",
    "abtasts": "abtaſtſ",
    "abtast": "abtaſt",
    "abwesen": "abweſen",
    "abzus": "abzuſ",
    "achts": "achtſ",
    "adels": "adels",
    "almosens": "almoſenſ",
    "almosen": "almoſen",
    "ameisens": "ameiſenſ",
    "ameisen": "ameiſen",
    "amtss": "amtsſ",
    "amts": "amts",
    "anges": "angeſ",
    "antis": "antiſ",
    "anwesen": "anweſen",
    "anzus": "anzuſ",
    "arrest": "arreſt",
    "asbest": "asbeſt",
    "assist": "aſſiſt",
    "atems": "atemſ",
    "atmos": "atmos",
    "atoms": "atomſ",
    "august": "auguſt",
    "autos": "autoſ",
    "babys": "babyſ",
    "bachs": "bachſ",
    "bades": "badeſ",
    "bahns": "bahnſ",
    "balls": "ballſ",
    "bands": "bandſ",
    "basis": "baſis",
    "baums": "baumſ",
    "beans": "beanſ",
    "befest": "befeſt",
    "beins": "beinſ",
    "belas": "belaſ",
    "bergs": "bergſ",
    "biers": "bierſ",
    "bilds": "bildſ",
    "blaus": "blauſ",
    "bleis": "bleiſ",
    "bluts": "blutſ",
    "bohrs": "bohrſ",
    "bonus": "bonus",
    "boots": "boots",
    "bords": "bordſ",
    "brats": "bratſ",
    "braus": "brauſ",
    "brems": "brems",
    "brots": "brotſ",
    "browser": "browſer",
    "bruts": "brutſ",
    "buchs": "buchſ",
    "bunts": "buntſ",
    "burgs": "burgſ",
    "büros": "büroſ",
    "chors": "chorſ",
    "christs": "chriſtſ",
    "christ": "chriſt",
    "codes": "codeſ",
    "dachs": "dachſ",
    "darms": "darmſ",
    "dazus": "dazuſ",
    "deutsch": "deutſch",
    "devisens": "deviſens",
    "devisen": "deviſen",
    "diebs": "diebſ",
    "diens": "dienſ",
    "dorfs": "dorfſ",
    "drehs": "drehſ",
    "dreis": "dreiſ",
    "dünns": "dünnſ",
    "edels": "edelſ",
    "eichs": "eichſ",
    "eiers": "eierſ",
    "erlös": "erlöſ",
    "ersts": "erſtſ",
    "erst": "erſt",
    "euros": "euroſ",
    "fachs": "fachſ",
    "fahrs": "fahrſ",
    "falls": "fallſ",
    "fangs": "fangſ",
    "farbs": "farbſ",
    "fehls": "fehlſ",
    "feins": "feinſ",
    "felds": "feldſ",
    "felss": "felsſ",
    "fels": "fels",
    "fernseh": "fernſeh",
    "fests": "feſtſ",
    "fest": "feſt",
    "fetts": "fettſ",
    "films": "filmſ",
    "fleisch": "fleiſch",
    "fliesens": "flieſenſ",
    "fliesen": "flieſen",
    "flugs": "flugſ",
    "fluss": "fluſs",
    "fluts": "flutſ",
    "fonds": "fonds",
    "forms": "formſ",
    "forts": "fortſ",
    "fotos": "fotoſ",
    "freis": "freiſ",
    "fress": "freſs",
    "fuchs": "fuchs",
    "fülls": "füllſ",
    "fünfs": "fünfſ",
    "gangs": "gangſ",
    "gasts": "gaſtſ",
    "gast": "gaſt",
    "gelds": "geldſ",
    "gemis": "gemiſ",
    "gemüses": "gemüſeſ",
    "gemüs": "gemüſ",
    "genes": "geneſ",
    "gerüs": "gerüſ",
    "gewissens": "gewiſſens",
    "gewiss": "gewiſſ",
    "gewis": "gewiſ",
    "gifts": "giftſ",
    "glass": "glasſ",
    "gleis": "gleis",
    "gletsch": "gletſch",
    "golds": "goldſ",
    "golfs": "golfſ",
    "grabs": "grabſ",
    "grass": "grasſ",
    "grobs": "grobſ",
    "großs": "großſ",
    "grüns": "grünſ",
    "haars": "haarſ",
    "halbs": "halbſ",
    "halss": "halsſ",
    "hals": "hals",
    "hands": "handſ",
    "hanfs": "hanfſ",
    "harns": "harnſ",
    "harts": "hartſ",
    "hauss": "hausſ",
    "haus": "haus",
    "hauts": "hautſ",
    "heils": "heils",
    "heims": "heimſ",
    "hells": "hellſ",
    "herbst": "herbſt",
    "herrch": "herrſch",
    "hilfs": "hilfs",
    "hirns": "hirnſ",
    "hochs": "hochſ",
    "hunds": "hunds",
    "höchsts": "höchſtſ",
    "höchst": "höchſt",
    "illus": "illuſ",
    "indus": "induſ",
    "inkasso": "inkaſſo",
    "invas": "invaſ",
    "invests": "inveſtſ",
    "invest": "inveſt",
    "ionis": "ioniſ",
    "jagds": "jagdſ",
    "jeans": "jeans",
    "jungs": "jungſ",
    "jurist": "juriſt",
    "kalbs": "kalbs",
    "kalts": "kaltſ",
    "kaross": "karoſſ",
    "katast": "kataſt",
    "kautschuks": "kautſchukſ",
    "kautschuk": "kautſchuk",
    "keils": "keilſ",
    "kerns": "kernſ",
    "kinos": "kinoſ",
    "kipps": "kippſ",
    "klassens": "klaſſenſ",
    "klassen": "klaſſen",
    "klatsch": "klatſch",
    "klebs": "klebſ",
    "knies": "knieſ",
    "kochs": "kochſ",
    "kokos": "kokos",
    "kopfs": "kopfſ",
    "kraus": "kraus",
    "krebs": "krebs",
    "kreis": "kreis",
    "kurs": "kurs",
    "käses": "käſeſ",
    "käse": "käſe",
    "kühls": "kühlſ",
    "lachs": "lachs",
    "lades": "ladeſ",
    "lands": "landſ",
    "langs": "langſ",
    "lasts": "laſtſ",
    "last": "laſt",
    "laufs": "laufſ",
    "lauts": "lautſ",
    "leers": "leerſ",
    "lehns": "lehnſ",
    "lehrs": "lehrſ",
    "leits": "leitſ",
    "lerns": "lernſ",
    "leses": "leſeſ",
    "lese": "leſe",
    "lochs": "lochſ",
    "lohns": "lohnſ",
    "lufts": "luftſ",
    "lusts": "luſtſ",
    "lust": "luſt",
    "luxus": "luxus",
    "längs": "längs",
    "lärms": "lärmſ",
    "mehrs": "mehrſ",
    "metas": "metaſ",
    "miets": "mietſ",
    "minus": "minus",
    "modes": "modeſ",
    "monds": "mondſ",
    "mords": "mords",
    "munds": "mundſ",
    "mülls": "müllſ",
    "nachs": "nachſ",
    "neuns": "neunſ",
    "nords": "nordſ",
    "nulls": "nullſ",
    "nährst": "nährſt",
    "obers": "oberſ",
    "obsts": "obſtſ",
    "obst": "obſt",
    "orgasmuss": "orgasmusſ",
    "orgasmus": "orgasmus",
    "ostas": "ostaſ",
    "palasts": "palaſtſ",
    "palast": "palaſt",
    "paläst": "paläſt",
    "paras": "paraſ",
    "penis": "penis",
    "pfirs": "pfirſ",
    "pflaster": "pflaſter",
    "plans": "planſ",
    "posts": "poſtſ",
    "post": "poſt",
    "preis": "preis",
    "press": "preſs",
    "priesters": "prieſterſ",
    "priester": "prieſter",
    "prüfs": "prüfſ",
    "quers": "querſ",
    "rands": "randſ",
    "raums": "raumſ",
    "reals": "realſ",
    "regist": "regiſt",
    "reins": "reinſ",
    "reits": "reitſ",
    "renns": "rennſ",
    "rests": "reſtſ",
    "rest": "reſt",
    "rings": "ringſ",
    "rohrs": "rohrſ",
    "rolls": "rollſ",
    "ruhes": "ruheſ",
    "runds": "rundſ",
    "sachs": "ſachſ",
    "sands": "ſandſ",
    "sechs": "ſechs",
    "seils": "ſeilſ",
    "semest": "ſemeſt",
    "sinus": "ſinus",
    "spars": "sparſ",
    "speise": "ſpeiſe",
    "späts": "ſpätſ",
    "stabs": "ſtabs",
    "stress": "streſs",
    "störs": "ſtörſ",
    "suchs": "ſuchſ",
    "südosts": "ſüdoſtſ",
    "südost": "ſüdoſt",
    "tages": "tages",
    "teils": "teilſ",
    "teles": "teleſ",
    "tests": "teſsſ",
    "test": "teſt",
    "texts": "texts",
    "tiefs": "tiefſ",
    "tiers": "tierſ",
    "todes": "todes",
    "trans": "tranſ",
    "trass": "traſſ",
    "turms": "turmſ",
    "turns": "turnſ",
    "ufers": "uferſ",
    "umges": "umgeſ",
    "umzus": "umzuſ",
    "unans": "unanſ",
    "unaus": "unaus",
    "unbes": "unbeſ",
    "uners": "unerſ",
    "unges": "ungeſ",
    "viels": "vielſ",
    "viers": "vierſ",
    "virus": "virus",
    "volls": "vollſ",
    "wachs": "wachs",
    "wahls": "wahlſ",
    "wahns": "wahnſ",
    "wahrs": "wahrſ",
    "walds": "waldſ",
    "wands": "wandſ",
    "warns": "warnſ",
    "wechs": "wechſ",
    "wehrs": "wehrſ",
    "weins": "weinſ",
    "weits": "weitſ",
    "welts": "weltſ",
    "werts": "wertſ",
    "wests": "weſtſ",
    "west": "weſt",
    "wetts": "wettſ",
    "wilds": "wildſ",
    "winds": "windſ",
    "wohls": "wohlſ",
    "wohns": "wohnſ",
    "wolfs": "wolfs",
    "wolls": "wollſ",
    "worts": "wortſ",
    "wunds": "wundſ",
    "wurfs": "wurfſ",
    "zahns": "zahnſ",
    "zehns": "zehnſ",
    "zeits": "zeitſ",
    "zells": "zellſ",
    "ziels": "zielſ",
    "ziers": "zierſ",
    "zins": "zins",
    "zolls": "zollſ",
    "zuges": "zugeſ",
    "zulassen": "zulaſſen",
    "zulassung": "zulaſſung",
    "zulass": "zulaſs",
    "zuzus": "zuzuſ",
    "zweis": "zweiſ",
    "zünds": "zündſ",
    "übers": "überſ",
    "achsels": "achſels",
    "achsel": "achſel",
    "achs": "achs",
    "akustiks": "akustikſ",
    "akustik": "akustik",
    "alts": "altſ",
    "amüs": "amüſ",
    "angsts": "angſtſ",
    "angst": "angſt",
    "anis": "anis",
    "anäst": "anäst",
    "apostels": "apostels",
    "apostel": "apostel",
    "aris": "ariſ",
    "arms": "armſ",
    "aufs": "aufſ",
    "bals": "balſ",
    "bars": "barſ",
    "bass": "baſs",
    "baus": "bauſ",
    "beis": "beiſ",
    "besser": "beſſer",
    "bios": "bioſ",
    "biss": "biſs",
    "blasens": "blaſenſ",
    "blasen": "blaſen",
    "blass": "blaſs",
    "blasp": "blasp",
    "blas": "blaſ",
    "bläss": "bläſſ",
    "bläs": "bläſ",
    "brust": "bruſt",
    "börsens": "börſenſ",
    "börsen": "börſen",
    "bürstens": "bürſtenſ",
    "bürst": "bürſt",
    "caes": "caeſ",
    "dars": "darſ",
    "diesels": "dieſelſ",
    "diesel": "dieſel",
    "diss": "disſ",
    "doms": "domſ",
    "dors": "dorſ",
    "dressurs": "dreſſurſ",
    "dressur": "dreſſur",
    "dreschs": "dreſchſ",
    "dresch": "dreſch",
    "drüs": "drüſ",
    "dursts": "durſtſ",
    "durst": "durſt",
    "ehes": "eheſ",
    "eins": "einſ",
    "eisens": "eiſenſ",
    "eisen": "eiſen",
    "eiss": "eisſ",
    "eis": "eis",
    "elast": "elaſt",
    "ends": "endſ",
    "ents": "entſ",
    "epis": "epiſ",
    "erbs": "erbſ",
    "erds": "erdſ",
    "ernsts": "ernſtſ",
    "ernst": "ernſt",
    "eros": "eroſ",
    "exist": "exiſt",
    "fals": "falſ",
    "fass": "faſs",
    "fersens": "ferſenſ",
    "fersen": "ferſen",
    "fessels": "feſſelſ",
    "fessel": "feſſel",
    "flaschens": "flaſchenſ",
    "flaschen": "flaſchen",
    "fors": "forſ",
    "fossils": "foſſilſ",
    "fossil": "foſſil",
    "fres": "fres",
    "fris": "friſ",
    "fros": "froſ",
    "fräs": "fräſ",
    "fäls": "fälſ",
    "fürs": "fürſ",
    "gass": "gasſ",
    "geists": "geiſtſ",
    "geist": "geiſt",
    "gerstens": "gerſtens",
    "gersten": "gerſten",
    "gips": "gips",
    "glas": "glas",
    "gras": "gras",
    "grusels": "gruſelſ",
    "grusel": "gruſel",
    "guss": "guſs",
    "guts": "gutſ",
    "gänses": "gänſeſ",
    "gänse": "gänſe",
    "hass": "haſs",
    "hers": "herſ",
    "heus": "heuſ",
    "hins": "hinſ",
    "hirs": "hirſ",
    "hofs": "hofſ",
    "hubs": "hubſ",
    "häus": "häuſ",
    "hörs": "hörſ",
    "hülsens": "hülſenſ",
    "hülsen": "hülſen",
    "iris": "iris",
    "kaisers": "kaiſerſ",
    "kaiser": "kaiſer",
    "kaps": "kapſ",
    "kaus": "kauſ",
    "kiesel": "kieſel",
    "kies": "kies",
    "kirschs": "kirſchſ",
    "kirsch": "kirſch",
    "klis": "kliſ",
    "klosters": "kloſterſ",
    "kloster": "kloſter",
    "knus": "knuſ",
    "kons": "konſ",
    "kors": "korſ",
    "kristalls": "kriſtallſ",
    "kristall": "kriſtall",
    "krisens": "kriſenſ",
    "krisen": "kriſen",
    "kunsts": "kunſtſ",
    "kunst": "kunſt",
    "kuts": "kutſ",
    "künstlers": "künſtlerſ",
    "künstler": "künſtler",
    "leas": "leaſ",
    "leis": "leiſ",
    "lins": "linſ",
    "loss": "losſ",
    "mais": "mais",
    "mans": "manſ",
    "marschs": "marſchſ",
    "marsch": "marſch",
    "mars": "mars",
    "maus": "maus",
    "meists": "meiſtſ",
    "meist": "meiſt",
    "menschens": "menſchenſ",
    "mens": "menſ",
    "mess": "meſs",
    "miss": "miſs",
    "mits": "mitſ",
    "mons": "monſ",
    "moos": "moos",
    "nasse": "naſſe",
    "nass": "naſs",
    "neus": "neuſ",
    "nots": "notſ",
    "nuss": "nuſs",
    "ochs": "ochsſ",
    "ohrs": "ohrſ",
    "orts": "orts",
    "osts": "oſtſ",
    "ost": "oſt",
    "papst": "papſt",
    "pass": "paſs",
    "paus": "pauſ",
    "pens": "penſ",
    "pers": "perſ",
    "phas": "phaſ",
    "phos": "phos",
    "phys": "phyſ",
    "pins": "pinſ",
    "piss": "piſſ",
    "plast": "plaſt",
    "plüsch": "plüſch",
    "pols": "polſ",
    "possess": "poſſeſſ",
    "posse": "poſſe",
    "präs": "präſ",
    "puls": "puls",
    "putschs": "putſchſ",
    "putsch": "putſch",
    "quas": "quaſ",
    "rads": "radſ",
    "rassens": "raſſenſ",
    "rats": "rats",
    "rauschs": "rauſchſ",
    "rausch": "rauſch",
    "reises": "reiſeſ",
    "reise": "reiſe",
    "ress": "reſſ",
    "riesens": "rieſenſ",
    "ries": "rieſ",
    "riss": "riſs",
    "rohs": "rohſ",
    "ross": "roſs",
    "rots": "rotſ",
    "rums": "rumſ",
    "russ": "ruſſ",
    "ruts": "rutſ",
    "räts": "rätſ",
    "rüst": "rüſt",
    "sais": "ſaiſ",
    "sees": "ſeeſ",
    "sehs": "ſehſ",
    "sens": "ſenſ",
    "sess": "seſſ",
    "skis": "ſkiſ",
    "spesens": "ſpeſenſ",
    "spesen": "ſpeſen",
    "subs": "ſubſ",
    "süds": "ſüdſ",
    "tats": "tatſ",
    "taus": "tauſ",
    "thes": "theſ",
    "tons": "tonſ",
    "tors": "torſ",
    "tots": "totſ",
    "tras": "traſ",
    "trosts": "troſtſ",
    "trost": "troſt",
    "türs": "türſ",
    "vers": "verſ",
    "vors": "vorſ",
    "waisens": "waiſenſ",
    "waisen": "waiſen",
    "wassers": "waſſerſ",
    "wasser": "waſſer",
    "webs": "webſ",
    "wegs": "wegſ",
    "weisens": "weiſenſ",
    "weisen": "weiſen",
    "wiesens": "wieſenſ",
    "wiesen": "wieſen",
    "wissens": "wiſſenſ",
    "wissen": "wiſſen",
    "wunschs": "wunſchſ",
    "wunsch": "wunſch",
    "wursts": "wurſtſ",
    "wurst": "wurſt",
    "zensurs": "zenſurſ",
    "zensur": "zenſur",
    "zers": "zerſ",
    "zugs": "zugſ",
    "zwischens": "zwiſchenſ",
    "zwischen": "zwiſchen",
    "ökos": "ökoſ",
    "abs": "abſ",
    "als": "alſ",
    "ans": "anſ",
    "arschs": "arſchſ",
    "arsch": "arſch",
    "ass": "aſſ",
    "bes": "beſ",
    "bus": "bus",
    "das": "das",
    "des": "deſ",
    "dis": "dis",
    "dosens": "doſenſ",
    "dosen": "doſen",
    "duschs": "duſchſ",
    "dusch": "duſch",
    "düsens": "düſenſ",
    "düsen": "düſen",
    "ers": "erſ",
    "ess": "eſs",
    "fas": "faſ",
    "fes": "feſ",
    "fischs": "fiſchſ",
    "fisch": "fiſch",
    "ges": "geſ",
    "hasens": "haſenſ",
    "hasen": "haſen",
    "hiss": "hiſs",
    "his": "hiſ",
    "hos": "hoſ",
    "ins": "inſ",
    "jus": "juſ",
    "kassens": "kaſſenſ",
    "kass": "kaſſ",
    "kas": "kaſ",
    "kessels": "keſſelſ",
    "kess": "keſſ",
    "kes": "kes",
    "kissens": "kiſſenſ",
    "kiss": "kiſſ",
    "kis": "kiſ",
    "kostens": "koſtenſ",
    "kost": "koſt",
    "kuss": "kuſs",
    "kus": "kuſ",
    "küst": "küſt",
    "las": "laſ",
    "listens": "liſtenſ",
    "list": "liſt",
    "los": "los",
    "lös": "löſ",
    "mis": "mis",
    "mos": "moſ",
    "mus": "muſ",
    "nasens": "naſenſ",
    "nasen": "naſen",
    "nes": "neſ",
    "nis": "niſ",
    "pes": "peſ",
    "risikos": "riſikoſ",
    "risiko": "riſiko",
    "rosens": "roſenſ",
    "rosen": "roſen",
    "tas": "taſ",
    "tes": "teſ",
    "tis": "tiſ",
    "ums": "umſ",
    "uns": "unſ",
    "urs": "urſ",
    "vis": "viſ",
    "wes": "weſ",
    "wüstens": "wüſtenſ",
    "wüsten": "wüſten",
    "zis": "ziſ",
    "zus": "zuſ",
    "öls": "ölſ",
}

_END_REPLACEMENTS = {
    "schtem": "ſchtem",
    "schten": "ſchten",
    "schter": "ſchter",
    "schtes": "ſchtes",
    "schte": "ſchte",
    "scht": "ſcht",

    "schers": "ſchers",
    "schem": "ſchem",
    "sches": "ſches",
    "scher": "ſcher",
    "sche": "ſche",
    "sch": "ſch",

    "sses": "ſses", # UNCERTAIN: adjective ending conficts

    "ssterem": "ſſterem",
    "ssteren": "ſſteren",
    "ssterer": "ſſterer",
    "ssteres": "ſſteres",
    "sstere": "ſſtere",
    "sster": "ſſter",

    "sstemem": "ſſtemem",
    "sstemen": "ſſtemen",
    "sstemer": "ſſtemer",
    "sstemes": "ſſtemes",
    "ssteme": "ſſteme",
    "sstem": "ſſtem",

    "sstenem": "ſſtenem",
    "sstenen": "ſſtenen",
    "sstener": "ſſtener",
    "sstenes": "ſſtenes",
    "sstene": "ſſtene",
    "ssten": "ſſten",

    "sstes": "ſſtes",
    "sste": "ſſte",
    "sst": "ſſt",

    "sen": "ſen",

    "sterem": "ſterem",
    "steren": "ſteren",
    "sterers": "ſterers",
    "sterer": "ſterer",
    "steres": "ſteres",
    "stere": "ſtere",
    "sters": "ſters",
    "ster": "ſter",

    "stemem": "ſtemem",
    "stemen": "ſtemen",
    "stemer": "ſtemer",
    "stemes": "ſtemes",
    "steme": "ſteme",
    "stems": "ſtems",
    "stem": "ſtem",

    "stenem": "ſtenem",
    "stenen": "ſtenen",
    "stener": "ſtener",
    "stenes": "ſtenes",
    "stene": "ſtene",
    "stens": "ſtens",
    "sten": "ſten",
    "stes": "ſtes",
    "stet": "ſtet",
    "ste": "ſte",
    "se": "ſe",
    "st": "ſt",

    # "chip" exception
    "schips": "schips",
    "chips": "chips",
    "schip": "schip",

    # "chor" and "chör" exceptions    
    "sschören": "ſschören",
    "sschores": "ſschores",
    "sschöre": "ſscöre",
    "sschors": "ſschors",
    "sschor": "ſschor",

    "schören": "schören",
    "schöres": "schöres",
    "schöre": "schöre",
    "schors": "schors",
    "schor": "schor",

    # -abel
    "ssabel": "ſſabel",
    "sabel": "ſabel",

    # -al
    "saler": "ſaler",
    "salem": "ſalem",
    "salen": "ſalen",
    "sales": "ſales",
    "sale": "ſale",
    "sals": "ſals",
    "sal": "ſal",

    # -am
    "samerem": "ſamerem",
    "sameren": "ſameren",
    "samerer": "ſamerer",
    "sameres": "ſameres",
    "samere": "ſamere",
    "samers": "ſamers",
    "samer": "ſamer",
    "samem": "ſamem",
    "samen": "ſamen",
    "sames": "ſames",
    "sams": "ſams",
    "same": "ſame",
    "sam": "ſam",

    # -gesamt
    "gesamtem": "geſamtem",
    "gesamten": "geſamten",
    "gesamter": "geſamter",
    "gesamtes": "geſamtes",
    "gesamte": "geſamte",
    "gesamt": "geſamt",
    
    # -amt
    "samterem": "ſamterem",
    "samteren": "ſamteren",
    "samterer": "ſamterer",
    "samteres": "ſamteres",
    "samtere": "ſamtere",
    "samter": "ſamter",
    "samtem": "ſamtem",
    "samten": "ſamten",
    "samtes": "samtes",
    "samte": "ſamte",
    "samts": "samts",
    "samt": "samt",

    # -ant
    "ssanterem": "ſſanterem",
    "ssanteren": "ſſanteren",
    "ssanterer": "ſſanterer",
    "ssanteres": "ſſanteres",
    "ssantere": "ſſantere",
    "ssanter": "ſſanter",
    "ssans": "ſſans",
    "ssantem": "ſſantem",
    "ssanten": "ſſanten",
    "ssantes": "ſſantes",
    "ssante": "ſſante",
    "ssants": "ſſants",
    "ssant": "ſſant",

    "santerem": "ſanterem",
    "santeren": "ſanteren",
    "santerer": "ſanterer",
    "santeres": "ſanteres",
    "santere": "ſantere",
    "santers": "ſanters",
    "santer": "ſanter",
    "santem": "ſantem",
    "santen": "ſanten",
    "santes": "ſantes",
    "sante": "ſante",
    "sants": "ſants",
    "sant": "ſant",

    # -an
    "ssans": "ſſans",
    "ssan": "ſſan",
    "sane": "ſane",
    "sans": "ſans",
    "san": "ſan",

    # -anz
    "sanz": "ſanz",

    # -är
    "ssärs": "ſſärs",
    "ssär": "ſſär",
    "särs": "ſärs",
    "sär": "ſär",

    # -arm
    "ssarms": "ſsarms",
    "ssarm": "ſsarm",
    "sarms": "sarms",
    "sarm": "sarm",

    # -at
    "ssats": "ſſats",
    "ssat": "ſſat",
    "sats": "ſats",
    "sat": "ſat",

    # -artig
    "ssartigerem": "ſsartigerem",
    "ssartigeren": "ſsartigeren",
    "ssartigerer": "ſsartigerer",
    "ssartigeres": "ſsartigeres",
    "ssartiger": "ſsartiger",
    "ssartiges": "ſsartiges",
    "ssartige": "ſsartige",
    "ssartig": "ſsartig",
    
    "sartigerem": "sartigerem",
    "sartigeren": "sartigeren",
    "sartigerer": "sartigerer",
    "sartigeres": "sartigeres",
    "sartiger": "sartiger",
    "sartiges": "sartiges",
    "sartige": "sartige",
    "sartig": "sartig",

    # -äugig
    "säugigem": "säugigem",
    "säugigen": "säugigen",
    "säugiger": "säugiger",
    "säugiges": "säugiges",
    "säugige": "säugige",
    "säugig": "säugig",

    # -e (-em(s)) (-en(s)) (-er(s))
    "sserers": "ſſerers",
    "sserer": "ſſerer",
    "sserem": "ſſerem",
    "sseren": "ſſeren",
    "sseres": "ſſeres",
    "ssere": "ſſere",
    "ssers": "ſſers",
    "sser": "ſſer",
    "ssems": "ſſems",
    "ssens": "ſſens",
    "ssem": "ſſem",
    "ssen": "ſſen",
    "sse": "ſſe",

    "serem": "ſerem",
    "seren": "ſeren",
    "serers": "ſerers",
    "serer": "ſerer",
    "seres": "ſeres",
    "sere": "ſere",
    "sers": "ſers",
    "ser": "ſer",
    "sems": "ſems",
    "sens": "ſens",
    "sem": "ſem",
    "sen": "ſen",
    "se": "ſe" ,

    # -ei
    "sei": "sei",

    # -eln(d)
    "sselndem": "ſſelndem",
    "sselnden": "ſſelnden",
    "sselnder": "ſſelnder",
    "sselndes": "ſſelndes",
    "sselnde": "ſſelnde",
    "sselnd": "ſſelnd",
    "sseln": "ſſeln",

    "selndem": "ſelndem",
    "selnden": "ſelnden",
    "selnder": "ſelnder",
    "selndes": "ſelndes",
    "selnde": "ſelnde",
    "selnd": "ſelnd",
    "seln": "ſeln",

    # -el (-eln)
    "sselers": "ſſelers",
    "sseler": "ſſeler",
    "ssele": "ſſele",
    "ssels": "ſſels",
    "sselt": "ſſelt",
    "ssel": "ſſel",

    "seler": "ſeler",
    "sele": "ſele",
    "sels": "ſels",
    "selt": "ſelt",
    "sel": "ſel",

    # -elchen
    "sselchens": "ſſelchens",
    "sselchen": "ſſelchen",
    "selchens": "ſelchens",
    "selchen": "ſelchen",

    # -ell
    "ssells": "ſſells",
    "ssell": "ſſell",
    "sells": "ſells",
    "sell": "ſell",

    # -end (MAY BE UNNECESSARY)
    "ssenderem": "ſſenderem",
    "ssenderen": "ſſenderen",
    "ssenderer": "ſſenderer",
    "ssenderes": "ſſenderes",
    "ssendere": "ſſendere",
    "ssenderm": "sſenderm",
    "ssendern": "sſendern",
    "ssenders": "sſenders",
    "ssendes": "ſſendes",
    "ssende": "ſſende",
    "ssend": "ſſend",

    "senderem": "ſenderem",
    "senderen": "ſenderen",
    "senderer": "ſenderer",
    "senderes": "ſenderes",
    "sendere": "ſendere",
    "senderm": "ſenderm",
    "sendern": "ſendern",
    "send": "ſend",

    # -enz
    "ssenzes": "ſſenzes",
    "ssenz": "ſſenz",
    "senzes": "ſenzes",
    "senz": "ſenz",

    # -erchen
    "sserchens": "ſſerchens",
    "sserchen": "ſſerchen",
    "serchens": "ſerchens",
    "serchen": "ſerchen",

    # -erei
    "ssereis": "ſſereis",
    "sserei": "ſſerei",
    "sereis": "ſereis",
    "serei": "ſerei",

    # -erl
    "sserls": "ſſerls",
    "sserl": "ſſerl",
    "serls": "ſerls",
    "serl": "ſerl",

    # -erlei
    "serlei": "ſerlei",

    # -ern
    "ssernes": "ſſernes",
    "sserns": "ſſerns",
    "ssern": "ſſern",
    
    "sernem": "ſernem",
    "sernen": "ſernen",
    "serner": "ſerner",
    "sernes": "ſernes",
    "serne": "ſerne",
    "serns": "ſerns",
    "sern": "ſern",

    # -ert
    "ssertem": "ſſertem",
    "sserten": "ſſerten",
    "sserter": "ſſerter", 
    "ssertes": "ſſertes", 
    "sserte": "ſſerte",
    "sserts": "ſſerts", 
    "ssert": "ſſert", 

    "sertem": "ſertem",
    "serten": "ſerten",
    "serter": "ſerter", 
    "sertes": "ſertes", 
    "serte": "ſerte",
    "serts": "ſerts", 
    "sert": "ſert",

    # -erweise
    "sserweise": "ſſerweise",

    "serweisem": "ſerweiſem",
    "serweisen": "ſerweiſen",
    "serweiser": "ſerweiſer",
    "serweises": "ſerweiſes",
    "serweise": "ſerweiſe",

    # -esk? -eſk? UNCERTAIN

    # -eur (french loanwords)
    "sseuren": "ſſeuren",
    "sseure": "ſſeure",
    "sseurs": "ſſeurs",
    "sseur": "ſſeur",

    "seuren": "ſeuren",
    "seure": "ſeure",
    "seurs": "ſeurs",
    "seur": "ſeur",

    # -euse (french loanwords)
    "sseusen": "ſſeuſen",
    "sseuse": "ſſeuſe",
    "seusen": "ſeuſen",
    "seuse": "ſeuſe",

    # -hausen
    "hausens": "hauſens",
    "hausen": "hauſen",

    # -i (-is)
    "ssis": "ſſis",
    "ssi": "ſſi",
    "sis": "ſis",
    "si": "ſi",

    # -iatrie
    "siatrie": "ſiatrie",

    # -ich
    "sichs": "ſichs",
    "sich": "ſich",

    # -ien
    "ssiens": "ſſiens",
    "ssien": "ſſien",
    "siens": "ſiens",
    "sien": "ſien",

    # -iert
    "ssierterem": "ſſierterem",
    "ssierteren": "ſſierteren",
    "ssierterer": "ſſierterer",
    "ssierteres": "ſſierteres",
    "ssiertere": "ſſiertere",
    "ssiertem": "ſſiertem",
    "ssierten": "ſſierten",
    "ssierter": "ſſierter",
    "ssiertes": "ſſiertes",
    "ssierte": "ſſierte",
    "ssiert": "ſſiert",

    "sierterem": "ſierterem",
    "sierteren": "ſierteren",
    "sierterer": "ſierterer",
    "sierteres": "ſierteres",
    "siertere": "ſiertere",
    "siertem": "ſiertem",
    "sierten": "ſierten",
    "sierter": "ſierter",
    "siertes": "ſiertes",
    "sierte": "ſierte",
    "siert": "ſiert",

    # -ier (-ieren)
    "ssierens": "ſſierens",
    "ssierers": "ſſierers",
    "ssieren": "ſſieren",
    "ssierer": "ſſierer",
    "ssiere": "ſſiere",
    "ssiers": "ſſiers",
    "ssier": "ſſier",

    "sierens": "ſierens",
    "sierers": "ſierers",
    "sieren": "ſieren",
    "sierer": "ſierer",
    "siere": "ſiere",
    "siers": "ſiers",
    "sier": "ſier",

    # -igt
    "ssigtem": "ſſigtem",
    "ssigten": "ſſigten",
    "ssigter": "ſſigter",
    "ssigtes": "ſſigtes",
    "ssigte": "ſſigte",
    "ssigt": "ſſigt",

    "sigtem": "ſigtem",
    "sigten": "ſigten",
    "sigter": "ſigter",
    "sigtes": "ſigtes",
    "sigte": "ſigte",
    "sigt": "ſigt",

    # -ig (-igen)
    "ssigens": "ſſigens",
    "ssigem": "ſſigem",
    "ssigen": "ſſigen",
    "ssiger": "ſſiger",
    "ssiges": "ſſiges",
    "ssige": "ſſiges",
    "ssig": "ſſig",

    "sigens": "ſigens",
    "sigem": "ſigem",
    "sigen": "ſigen",
    "siger": "ſiger",
    "siges": "ſiges",
    "sige": "ſige",
    "sig": "ſig",

    # -igst
    "ssigstem": "ſſigſtem",
    "ssigsten": "ſſigſten",
    "ssigster": "ſſigſter",
    "ssigstes": "ſſigſtes",
    "ssigste": "ſſigſte",
    "ssigst": "ſſigſt",

    "sigstem": "ſigſtem",
    "sigsten": "ſigſten",
    "sigster": "ſigſter",
    "sigstes": "ſigſtes",
    "sigste": "ſigſte",
    "sigst": "ſigſt",

    # -igkeit
    "ssigkeiten": "ſſigkeiten",
    "ssigkeit": "ſſigkeit",
    "sigkeiten": "ſigkeiten",
    "sigkeit": "ſigkeit",

    # -ik
    "ssik": "ſſik",
    "sik": "ſik",

    # -iker
    "ssikern": "ſſikern",
    "ssikers": "ſſikers",
    "ssiker": "ſſiker",
    "sikern": "ſikern",
    "sikers": "ſikers",
    "siker": "ſiker",

    # -in
    "ssins": "ſſins",
    "ssin": "ſſin",
    "sins": "ſins",
    "sin": "ſin",

    # -ine
    "ssinen": "ſſinen",
    "ssiner": "ſſiner",
    "ssine": "ſſine",
    "sinen": "ſinen",
    "siner": "ſiner",
    "sine": "ſine",

    # -ing
    "ssings": "ſſings",
    "ssing": "ſſing",
    "sings": "ſings",
    "sing": "ſing",

    # -ion 
    "sionen": "ſionen",
    "sions": "ſions",
    "sion": "ſion",

    # -iren
    "siren": "ſiren",

    # -isierung
    "isierungen": "iſierungen",
    "isierung": "iſierung",

    # -ist
    "ssisten": "ſſiſten",
    "ssists": "ſſiſts",
    "ssist": "ſſiſt",
    "sisten": "ſiſten",
    "sists": "ſiſts",
    "sist": "ſiſt",

    # -istisch
    "sistischerem": "ſiſtiſcherem",
    "sistischeren": "ſiſtiſcheren",
    "sistischerer": "ſiſtiſcherer",
    "sistischeres": "ſiſtiſcheres",
    "sistischere": "ſiſtiſchere",
    "sistischers": "ſiſtiſchers",
    "sistischem": "ſiſtiſchem",
    "sistischen": "ſiſtiſchen",
    "sistischer": "ſiſtiſcher",
    "sistisches": "ſiſtiſches",
    "sistische": "ſiſtiſche",
    "sistisch": "ſiſtiſch",

    "istischerem": "iſtiſcherem",
    "istischeren": "iſtiſcheren",
    "istischerer": "iſtiſcherer",
    "istischeres": "iſtiſcheres",
    "istischere": "iſtiſchere",
    "istischers": "iſtiſchers",
    "istischem": "iſtiſchem",
    "istischen": "iſtiſchen",
    "istischer": "iſtiſcher",
    "istisches": "iſtiſches",
    "istische": "iſtiſche",
    "istisch": "iſtiſch",

    # -ität
    "sität": "ſität",

    # -iter
    "siters": "ſiters",
    "siter": "ſiter",  

    # -itis
    "sitis": "ſitis",

    # -ivst
    "ssivsterem": "ſſivſterem",
    "ssivsteren": "ſſivſteren",
    "ssivsterer": "ſſivſterer",
    "ssivsteres": "ſſivſteres",
    "ssivstere": "ſſivſtere",
    "ssivstem": "ſſivſtem",
    "ssivsten": "ſſivſten",
    "ssivster": "ſſivſter",
    "ssivstes": "ſſivſtes",
    "ssivste": "ſſivſte",
    "ssivst": "ſſivſt",

    "sivsterem": "ſivſterem",
    "sivsteren": "ſivſteren",
    "sivsterer": "ſivſterer",
    "sivsteres": "ſivſteres",
    "sivstere": "ſivſtere",
    "sivstem": "ſivſtem",
    "sivsten": "ſivſten",
    "sivster": "ſivſter",
    "sivstes": "ſivſtes",
    "sivste": "ſivſte",
    "sivst": "ſivſt",

    # -iv
    "ssiverem": "ſſiverem",
    "ssiveren": "ſſiveren",
    "ssiverer": "ſſiverer",
    "ssiveres": "ſſiveres",
    "ssivere": "ſſivere",
    "ssivem": "ſſivem",
    "ssiven": "ſſiven",
    "ssiver": "ſſiver",
    "ssives": "ſſives",
    "ssive": "ſſive",
    "ssiv": "ſſiv",

    "siverem": "ſiverem",
    "siveren": "ſiveren",
    "siverer": "ſiverer",
    "siveres": "ſiveres",
    "sivere": "ſivere",
    "sivem": "ſivem",
    "siven": "ſiven",
    "siver": "ſiver",
    "sives": "ſives",
    "sive": "ſive",
    "siv": "ſiv",


    # -ken
    "sken": "sken",

    # -köpfig
    "sköpfigers": "sköpfigers",
    "sköpfigem": "sköpfigem",
    "sköpfigen": "sköpfigen",
    "sköpfiger": "sköpfiger",
    "sköpfiges": "sköpfiges",
    "sköpfige": "sköpfige",
    "sköpfig": "sköpfig",

    # -kunde
    "sskunden": "ſskunden",
    "sskunde": "ſskunde",
    "skunden": "skunden",
    "skunde": "skunde",

    # -lyse
    "lysen": "lyſen",
    "lyse": "lyſe",

    # -oid
    "ssoidem": "ſſoidem",
    "ssoiden": "ſſoiden",
    "ssoider": "ſſoider",
    "ssoides": "ſſoides",
    "ssoide": "ſſoide",
    "ssoids": "ſſoids",
    "ssoid": "ſſoid",

    "soidem": "ſoidem",
    "soiden": "ſoiden",
    "soider": "ſoider",
    "soides": "ſoides",
    "soide": "ſoide",
    "soids": "ſoids",
    "soid": "ſoid",

    # -ologie
    "sologien": "ſologien",
    "sologie": "ſologie",


    # -ös
    "ösens": "öſens",
    "ösern": "öſern",
    "ösers": "öſers",
    "ösem": "öſem",
    "ösen": "öſen",
    "öser": "öſer",
    "öses": "öſes",
    "öse": "öſe",
    "ös": "ös",

    # -pflichtig
    "sspflichtigem": "ſspflichtigem",
    "sspflichtigen": "ſspflichtigen",
    "sspflichtiger": "ſspflichtiger",
    "sspflichtiges": "ſspflichtiges",
    "sspflichtige": "ſspflichtige",
    "sspflichtig": "ſspflichtig",

    "spflichtigem": "spflichtigem",
    "spflichtigen": "spflichtigen",
    "spflichtiger": "spflichtiger",
    "spflichtiges": "spflichtiges",
    "spflichtige": "spflichtige",
    "spflichtig": "spflichtig",

    # -phobie
    "sphobien": "sphobien",
    "sphobie": "sphobie",


    # -seits
    "sseits": "sſeits",
    "seits": "ſeits",

    # -ski
    "ski": "ſki",

    # -stämmig
    "stämmigerem": "ſtämmigerem",
    "stämmigeren": "ſtämmigeren",
    "stämmigerer": "ſtämmigerer",
    "stämmigeres": "ſtämmigeres",
    "stämmigers": "ſtämmigers",
    "stämmigem": "ſtämmigem",
    "stämmigen": "ſtämmigen",
    "stämmiger": "ſtämmiger",
    "stämmiges": "ſtämmiges",
    "stämmige": "ſtämmige",
    "stämmig": "ſtämmig",

    # -stein
    "ssteiners": "sſteiners",
    "ssteinem": "sſteinem",
    "ssteinen": "sſteinen",
    "ssteiner": "sſteiner",
    "ssteines": "sſteines",
    "ssteine": "sſteine",
    "ssteins": "sſteins",
    "sstein": "sſtein",

    "steiners": "ſteiners",
    "steinem": "ſteinem",
    "steinen": "ſteinen",
    "steiner": "ſteiner",
    "steines": "ſteines",
    "steine": "ſteine",
    "steins": "ſteins",
    "stein": "ſtein",

    # -tätigt
    "stätigtem": "ſtätigtem",
    "stätigten": "ſtätigten",
    "stätigter": "ſtätigter",
    "stätigtes": "ſtätigtes",
    "stätigte": "ſtätigte",
    "stätigt": "ſtätigt",

    # -tätig
    "stätigers": "stätigers",
    "stätigem": "stätigem",
    "stätiger": "stätiger",
    "stätiges": "stätiges",
    "stätige": "stätige",
    "stätig": "stätig",

    # -tik UNCERTAIN
    "stiken": "stiken",
    "stik": "stik",

    # -tion
    "stionen": "stionen",
    "stion": "stion",

    # -tum
    "stums": "stums",
    "stum": "stum",

    # -um
    "ssums": "ſſums",
    "ssum": "ſſum",
    "sums": "ſums",
    "sum": "ſum",

    # -ung
    "ssungen": "ſſungen",
    "ssung": "ſſung",
    "sungen": "ſungen",
    "sung": "ſung",

    # -urie
    "surie": "ſurie",
}

_dict_processed = False

UNKNOWN_S = "╳"

def _process_dict():
    global _REPLACEMENTS, _START_REPLACEMENTS, _END_REPLACEMENTS, _dict_processed
    if _dict_processed:
        return
    _REPLACEMENTS = {
        key.replace("s", UNKNOWN_S): value
        for key, value in _REPLACEMENTS.items()
    }
    _START_REPLACEMENTS = {
        key.replace("s", UNKNOWN_S): value
        for key, value in _START_REPLACEMENTS.items()
    }
    _END_REPLACEMENTS = {
        key.replace("s", UNKNOWN_S): value
        for key, value in _END_REPLACEMENTS.items()
    }

def german_conversion(text):
    _process_dict()
    SHORT_S_ALWAYS_BEFORE_Z = False # False after 1901.
    
    clean_text = text.lower().replace("s", UNKNOWN_S)
    
    # applies simple start patterns.
    if clean_text[0] == UNKNOWN_S:
        clean_text = "ſ" + clean_text[1:]

    # any unknown S that comes before many consonants will be a short S.
    if SHORT_S_ALWAYS_BEFORE_Z:
        pattern = f"{UNKNOWN_S}(?=[aäceioöp{UNKNOWN_S}tuüyAÄCEIOÖPTUÜY])"
    else:
        pattern = f"{UNKNOWN_S}(?=[aäceioöp{UNKNOWN_S}tuüyzAÄCEIOÖPTUÜYZ])"

    uncertain_indices = [m.start() for m in re.finditer(pattern, clean_text)]
    short_s_indices = [
        i for i, char in enumerate(clean_text)
        if char == UNKNOWN_S and i not in uncertain_indices
    ]
    for i in short_s_indices:
        clean_text = clean_text[:i] + "s" + clean_text[i + 1: ]


    for key, replacement in _REPLACEMENTS.items():
        if UNKNOWN_S not in clean_text:
            break
        clean_text = smart_replace(clean_text, key, replacement)

    # applies end spelling patterns.
    if clean_text[-1] in [UNKNOWN_S, "ſ"]:
        clean_text = clean_text[:-1] + "s"

    #if clean_text.endswith(f"{UNKNOWN_S}ch"):
    #    clean_text = clean_text[:-3] + "ſch"
    if clean_text[:-1].endswith(f"{UNKNOWN_S}ch"):
        clean_text = clean_text[:-4] + "ſch" + clean_text[-1]
    elif clean_text[:-1].endswith(f"{UNKNOWN_S}{UNKNOWN_S}"):
        clean_text = clean_text[:-3] + "ſſ" + clean_text[-1]

    for key, replacement in _END_REPLACEMENTS.items():
        clean_text = smart_replace(
            clean_text, key, replacement, restrict_to_end=True
        )
    
    clean_text = clean_text.replace(f"{UNKNOWN_S}s", "ſs")
    clean_text = clean_text.replace(f"s{UNKNOWN_S}", "sſ")

    for key, replacement in _START_REPLACEMENTS.items():
        clean_text = smart_replace(
            clean_text, key, replacement, restrict_to_start=True
        )

    clean_text = clean_text.replace(f"{UNKNOWN_S}s", "ſs")
    clean_text = clean_text.replace(f"s{UNKNOWN_S}", "sſ")

    return clean_text

def smart_replace(
    text,
    search_term,
    replacement,
    restrict_to_start=False,
    restrict_to_end=False,
):
    s_indices = [
        i for i, char
        in enumerate(replacement)
        if char in f"sſ"
    ]
    if len(s_indices) == 0 or len(search_term) > len(text):
        return text

    old_snippet = ""
    if len(search_term) < len(text):
        if restrict_to_end:
            old_snippet = text[:-len(search_term)]
            text = text[-len(search_term):]
        elif restrict_to_start:
            old_snippet = text[len(search_term):]
            text = text[:len(search_term)]

    n_unknowns = len(s_indices)
    if n_unknowns <= 1:
        text = text.replace(search_term, replacement)
        return old_snippet + text if restrict_to_end else text + old_snippet

    combinations = itertools.product([True, False], repeat=n_unknowns)
    combinations = [c for c in combinations if any(c)]
    keys = []
    for combo in combinations:
        #print(combo)
        new_string = list(replacement)
        for i, make_unknown in zip(s_indices, combo):
            if make_unknown:
                new_string[i] = UNKNOWN_S
        keys.append("".join(new_string))
    
    for key in keys:
        text = text.replace(key, replacement)

    return old_snippet + text if restrict_to_end else text + old_snippet

